### ISSUE TITLE
After two months without commits cron workflows get disabled

### ISSUE THREAD

**Issue by Niklp09** [minetest-mirrors/minetest-mirrors#10]
Fix no1: Push anything in this repo
Fix no2: Buckaroo's migration idea (IDK)

**Comment by BuckarooBanzay** [comment]
> _might_ fix

**Comment by Niklp09** [comment]
:laughing:

**Comment by Niklp09** [comment]
Done via https://github.com/minetest-mirrors/minetest-mirrors/commit/347318c4a951cae5823b8389c053b3b84febc223
